### ISSUE TITLE
Error in running python helper class

### ISSUE THREAD

**Issue by faysalhossain2007** [quarkslab/aosp_dataset#1]
I have installed python 3.10 and run `pip install .` . However, when I try to run the helper class, I got the following error:

```
Traceback (most recent call last):
  File "/media/faysal-gpu/easystore/ucsb/aosp_dataset-master/main.py", line 4, in <module>
    cve_2012_6701 = aosp_dataset.AospCve(
  File "pydantic/main.py", line 332, in pydantic.main.BaseModel.__init__
TypeError: __init__() takes exactly 1 positional argument (2 given)
```

**Comment by DarkaMaul** [comment]
Fixed by fe75afb5b661d39d30a9ac2ceccdee5561a1bd4b and a5808a65d1bdd34390f9e2042b3d7da7398726e6
